# Generated by Django 6.0.4 on 2026-04-18 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('disease', models.CharField(max_length=100)),
                ('cure', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plant_image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
