# Generated by Django 6.0.4 on 2026-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraApp', '0003_remove_profile_address_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_cured',
            field=models.BooleanField(default=False),
        ),
    ]
